project_id = "urjzuydkyjgvzbmeaugx"

[functions.chat]
verify_jwt = true

[functions.studio-image]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.process-knowledge]
verify_jwt = true
